version: "3"
services:

  nginx-budscraper:
    image: nginx:alpine
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports: 
      - "8085:80"
    volumes: 
     - '/home/ubuntu/container-program-files/budscraper.io/temp/o:/var/www/html/o'

  php-budscraper:
    image: php:fpm-alpine
    build:
      context: .
      dockerfile: dockerfile-php
    restart: always
    depends_on:
      - nginx-budscraper
    volumes: 
     - '/home/ubuntu/container-program-files/budscraper.io/temp/o:/var/www/html/o'
