version: "3"
services:

  nginx:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports: 
      - "8085:80"
    networks:
      - internal
    volumes: 
     - '/temp/o:/var/www/html/o'

  php:
    build:
      context: .
      dockerfile: dockerfile-php
    restart: always
    networks:
      - internal
    depends_on:
      - nginx
    volumes: 
     - '/temp/o:/var/www/html/o'
      
networks:
  internal:
    driver: bridge